Add support for arbitrary single-letter tags in Filter
nostr-sdk/nostr-sdk-ios pull request #154
Opened 2024-05-05 03:21 UTC by tyiu

https://github.com/nostr-protocol/nips/blob/4fa65b81cede9eaf8375d4f92bc80cf298190e0c/01.md#from-client-to-relay-sending-events-and-creating-subscriptions

2024-05-05 03:24 UTC, tyiu commented on Sources/NostrSDK/Filter.swift
> +public struct Filter: Encodable, Hashable, Equatable {
We don't decode Filter anywhere, so I changed it to be only `Encodable`.

2024-05-05 03:24 UTC, tyiu commented on Sources/NostrSDK/Filter.swift
> +    /// If `tags` contains an `e` tag and `events` is also provided, `events` takes precedence.
I kept in `events` and `pubkeys` for backwards compatibility, but also developer ergonomics. Let me know if you think this is a bad idea.

2024-05-19 12:01 UTC, bryanmontz requested changes

2024-05-19 12:14 UTC, tyiu commented on Sources/NostrSDK/Filter.swift
> +        init?(intValue: Int) {
It's declaration is required by the `CodingKey` protocol. The compiler doesn't like it if it's not there. Per the documentation of this initializer, it says

```swift
    /// Creates a new instance from the specified integer.
    ///
    /// If the value passed as `intValue` does not correspond to any instance of
    /// this type, the result is `nil`.
    ///
    /// - parameter intValue: The integer value of the desired key.
    init?(intValue: Int)
```

2024-05-19 12:22 UTC, tyiu commented on Sources/NostrSDK/Filter.swift
> +    var isEnglishLetter: Bool {
I think "Latin script" might be too broad.

>The Latin script is the basis of the [International Phonetic Alphabet](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet), and the 26 most widespread letters are the letters contained in the [ISO basic Latin alphabet](https://en.wikipedia.org/wiki/ISO_basic_Latin_alphabet), which are the same letters as the [English alphabet](https://en.wikipedia.org/wiki/English_alphabet).

Maybe `isBasicLatinAlphabet` is better.

2024-05-19 12:45 UTC, tyiu commented on Sources/NostrSDK/Filter.swift
> +    /// a list of tag values that are referenced by single English-alphabet letter tag names
Changed it to "basic Latin letter" instead.
https://en.wikipedia.org/wiki/ISO_basic_Latin_alphabet

2024-05-19 12:45 UTC, tyiu commented on Sources/NostrSDK/Filter.swift
> +    ///   - tags: a list of tag values that are referenced by single English-alphabet letter tag names
Changed it to "basic Latin letter" instead.
https://en.wikipedia.org/wiki/ISO_basic_Latin_alphabet

2024-05-19 12:45 UTC, tyiu commented on Sources/NostrSDK/Filter.swift
> +    /// Returns `nil` if `tags` contains tag names that are not in the English-alphabet of A-Z or a-z.
Changed it to "basic Latin letter" instead.
https://en.wikipedia.org/wiki/ISO_basic_Latin_alphabet

2024-05-19 13:32 UTC, bryanmontz approved these changes

2024-05-19 17:36 UTC, bryanmontz commented
@tyiu Feel free to merge this one after resolving conflicts.

2024-05-19 21:01 UTC, merged